# development docker-compose file
# In other environments, you use the docker-compose.deployment.yml file
services:
  api:
    container_name: api-blokid
    image: blokid-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/api-blokid/logs
      - ./database-backups:/api-blokid/prisma/backups
    networks:
      - blokid-network

  database:
    image: mysql:8.0.24
    container_name: db-blokid
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-12345678}
      MYSQL_DATABASE: blokid-esp
      MYSQL_USER: sotadev
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-12345678}
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - blokid-network

networks:
  blokid-network:
    driver: bridge
