services:
  api:
    container_name: api-blokid
    image: blokid-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/api-blokid/logs
      - ./database-backups:/api-blokid/prisma/backups
    networks:
      - blokid-network

  rabbitmq:
    image: rabbitmq:alpine
    container_name: blokid-rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management plugin port
    networks:
      - blokid-network

networks:
  blokid-network:
    driver: bridge
