import { PartialType } from '@nestjs/swagger';
import { FootprintAction, FootprintElement, PriorityLevel } from '@prisma/client';
import { PaginationQueryDto } from 'src/core/platform/dtos';
import { PropertyDto } from 'src/decorators';

// Auto generated by tools/generate-dtos.ts at 2025-04-18T07:02:31.446Z
// ****************************** Base Footprint response dto ******************************
export class BaseFootprintResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  action: FootprintAction;

  @PropertyDto()
  element: FootprintElement;

  @PropertyDto()
  actionDetail: string;

  @PropertyDto()
  deviceUsed: string;

  @PropertyDto()
  priorityLevel?: PriorityLevel;

  @PropertyDto()
  intentScore: number;

  @PropertyDto()
  confidence: number;

  @PropertyDto()
  personId?: number;

  @PropertyDto()
  createdAt: Date;
}

// ****************************** GET Footprint dto ******************************
export class GetFootprintDetailResponseDto extends BaseFootprintResponseDto {
  // Add more fields if needed such as relations
}

export class GetFootprintListResponseDto extends BaseFootprintResponseDto {
  // Add more fields if needed such as relations
}

export class GetFootprintListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: FootprintAction,
    required: false,
    validated: true,
    structure: 'enum',
  })
  action: FootprintAction;

  @PropertyDto({
    type: FootprintElement,
    required: false,
    validated: true,
    structure: 'enum',
  })
  element: FootprintElement;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  actionDetail: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  deviceUsed: string;

  @PropertyDto({
    type: PriorityLevel,
    required: false,
    validated: true,
    structure: 'enum',
  })
  priorityLevel: PriorityLevel;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  intentScore: number;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  confidence: number;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  personId: number;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;
}

// ****************************** CREATE Footprint dto ******************************
// todo: delete this line if you have corrected the dto
export class CreateFootprintBodyDto {
  @PropertyDto({
    type: FootprintAction,
    required: true,
    validated: true,
    structure: 'enum',
  })
  action: FootprintAction;

  @PropertyDto({
    type: FootprintElement,
    required: true,
    validated: true,
    structure: 'enum',
  })
  element: FootprintElement;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  actionDetail: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  deviceUsed: string;

  @PropertyDto({
    type: PriorityLevel,
    required: true,
    validated: true,
    structure: 'enum',
  })
  priorityLevel: PriorityLevel;

  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  intentScore: number;

  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  confidence: number;

  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  personId: number;
}

export class CreateFootprintResponseDto extends BaseFootprintResponseDto {}

// ****************************** UPDATE Footprint dto ******************************
// todo: delete this line if you have corrected the dto
export class UpdateFootprintBodyDto extends PartialType(CreateFootprintBodyDto) {
  // User OmitType if needed
}

export class UpdateFootprintResponseDto extends BaseFootprintResponseDto {}

// ****************************** More Footprint dto below ******************************
