import { PartialType } from '@nestjs/swagger';
import { PaginationQueryDto } from 'src/core/platform/dtos';
import { PropertyDto } from 'src/decorators';

// Auto generated by tools/generate-dtos.ts at 2025-04-15T10:10:13.696Z
// ****************************** Base ExecutiveCompany response dto ******************************
export class BaseExecutiveCompanyResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  businessId: number;

  @PropertyDto()
  name: string;

  @PropertyDto()
  geography: string;

  @PropertyDto()
  createdAt: Date;
}

// ****************************** GET ExecutiveCompany dto ******************************
export class GetExecutiveCompanyDetailResponseDto extends BaseExecutiveCompanyResponseDto {
  // Add more fields if needed such as relations
}

export class GetExecutiveCompanyListResponseDto extends BaseExecutiveCompanyResponseDto {
  // Add more fields if needed such as relations
}

export class GetExecutiveCompanyListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  businessId: number;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  name: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  geography: string;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;
}

// ****************************** CREATE ExecutiveCompany dto ******************************
// todo: delete this line if you have corrected the dto
export class CreateExecutiveCompanyBodyDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  businessId: number;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  name: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  geography: string;
}

export class CreateExecutiveCompanyResponseDto extends BaseExecutiveCompanyResponseDto {}

// ****************************** UPDATE ExecutiveCompany dto ******************************
// todo: delete this line if you have corrected the dto
export class UpdateExecutiveCompanyBodyDto extends PartialType(
  CreateExecutiveCompanyBodyDto,
) {
  // User OmitType if needed
}

export class UpdateExecutiveCompanyResponseDto extends BaseExecutiveCompanyResponseDto {}

// ****************************** More ExecutiveCompany dto below ******************************
