import { MulterFile } from 'src/core/platform';
import { PaginationQueryDto } from 'src/core/platform/dtos';
import { PropertyDto } from 'src/decorators';

// Auto generated by tools/generate-dtos.ts at 2025-04-16T09:57:36.312Z
// ****************************** Base ExecutiveUpload response dto ******************************
export class BaseExecutiveUploadResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  fileName: string;

  @PropertyDto()
  filePath: string;

  @PropertyDto()
  quantity: number;

  @PropertyDto()
  storageLink: string;

  @PropertyDto()
  executiveCompanyId: number;

  @PropertyDto()
  createdAt: Date;
}

// ****************************** GET ExecutiveUpload dto ******************************
export class GetExecutiveUploadDetailResponseDto extends BaseExecutiveUploadResponseDto {
  // Add more fields if needed such as relations
}

export class GetExecutiveUploadListResponseDto extends BaseExecutiveUploadResponseDto {
  // Add more fields if needed such as relations
}

export class GetExecutiveUploadListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  fileName: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  filePath: string;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  quantity: number;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  storageLink: string;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  executiveCompanyId: number;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;
}

// ****************************** CREATE ExecutiveUpload dto ******************************
export class CreateExecutiveUploadBodyDto {
  @PropertyDto({
    type: 'file',
    required: true,
    validated: true,
  })
  file: MulterFile;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
    description: `In MVP, target company id is not required`,
  })
  targetCompanyId: number;
}

export class CreateExecutiveUploadResponseDto extends BaseExecutiveUploadResponseDto {}

// ****************************** saveExecutiveUpload ******************************
export class SaveExecutiveUploadBodyDto {
  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
    description: `Upload file id`,
  })
  id: number;
}

export class SaveExecutiveUploadResponseDto {}

// ****************************** enrichExecutiveUpload ******************************
export class EnrichExecutiveUploadBodyDto {
  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
    description: `Upload file id`,
  })
  id: number;
}

export class EnrichExecutiveUploadResponseDto {
  @PropertyDto()
  enrichSuccess: number;

  @PropertyDto()
  enrichFail: number;
}
