import { PropertyDto } from 'src/decorators';

// Auto generated by tools/generate-dtos.ts at 2025-04-16T09:17:02.182Z
// ****************************** Base ExecutiveUpload response dto ******************************
export class BaseExecutiveUploadResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  fileName: string;

  @PropertyDto()
  filePath: string;

  @PropertyDto()
  quantity: number;

  @PropertyDto()
  storageLink: string;

  @PropertyDto()
  executiveCompanyId: number;

  @PropertyDto()
  createdAt: Date;
}
